import { useState, useEffect, useRef } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { consultationsApi } from '@/api/consultations'
import { reportsApi } from '@/api/reports'
import { apiClient } from '@/api/client'
import { Save, CheckCircle, Loader2, Download } from 'lucide-react'
import toast from 'react-hot-toast'
import { formatSoapField } from '@/utils'

interface Props {
  consultationId: string
}

export default function SOAPEditor({ consultationId }: Props) {
  const qc = useQueryClient()
  const [fields, setFields] = useState({ 
    subjective: '', 
    objective: '', 
    assessment: '', 
    plan: '',
    medications: [] as any[],
    follow_up_needed: false,
    follow_up_days: 0
  })
  const [reportId, setReportId] = useState<string | null>(null)
  const [synced, setSynced] = useState(false)
  const [reportStatus, setReportStatus] = useState<string>('draft')
  const [isAutoSaving, setIsAutoSaving] = useState(false)
  const lastSavedFields = useRef(JSON.stringify(fields))

  const { data: reportData, isLoading: reportLoading } = useQuery({
    queryKey: ['report', consultationId],
    queryFn: async () => {
      try {
        return await consultationsApi.getReport(consultationId)
      } catch (e) {
        return await apiClient.get(`/reports/${consultationId}`).then(r => r.data)
      }
    },
    onSuccess: (data: any) => {
      if (data && !data.error) {
        const loaded = {
          subjective: formatSoapField(data.subjective),
          objective: formatSoapField(data.objective),
          assessment: formatSoapField(data.assessment),
          plan: formatSoapField(data.plan),
          medications: data.medications || [],
          follow_up_needed: !!data.follow_up_needed,
          follow_up_days: data.follow_up_days || 0
        }
        setFields(loaded)
        lastSavedFields.current = JSON.stringify(loaded)
        setReportStatus(data.status || 'draft')
        setReportId(data.report_id || null)
        setSynced(true)
      }
    },
  } as any)

  useEffect(() => {
    if (!reportData) return

    const data = reportData as any
    const loaded = {
      subjective: formatSoapField(data.subjective),
      objective: formatSoapField(data.objective),
      assessment: formatSoapField(data.assessment),
      plan: formatSoapField(data.plan),
      medications: data.medications || [],
      follow_up_needed: !!data.follow_up_needed,
      follow_up_days: data.follow_up_days || 0
    }

    setFields(loaded)
    lastSavedFields.current = JSON.stringify(loaded)
    setReportStatus(data.status || 'draft')
    setReportId(data.report_id || null)
    setSynced(true)
  }, [reportData])

  const saveMut = useMutation({
    mutationFn: async () => {
      try {
        return await consultationsApi.updateReport(consultationId, fields as any)
      } catch (e) {
        return await reportsApi.update(consultationId, fields as any)
      }
    },
    onSuccess: (data: any) => {
      lastSavedFields.current = JSON.stringify(fields)
      setIsAutoSaving(false)
      if (data?.report_id) setReportId(data.report_id)
      qc.invalidateQueries({ queryKey: ['reports'] })
      qc.invalidateQueries({ queryKey: ['report', consultationId] })
    },
    onError: () => setIsAutoSaving(false),
  })

  // 10s Auto-save Logic
  useEffect(() => {
    const timer = setInterval(() => {
      const current = JSON.stringify(fields)
      if (current !== lastSavedFields.current && fields.subjective.length > 0) {
        setIsAutoSaving(true)
        saveMut.mutate()
      }
    }, 10000)

    return () => clearInterval(timer)
  }, [fields, saveMut])

  const generateMut = useMutation({
    mutationFn: () => (consultationsApi as any).generateSoap?.(consultationId) ?? Promise.reject('Not implemented'),
    onSuccess: (data: any) => {
      if (data && !data.error) {
        const generated = {
          subjective: formatSoapField(data.subjective),
          objective: formatSoapField(data.objective),
          assessment: formatSoapField(data.assessment),
          plan: formatSoapField(data.plan),
          medications: data.medications || [],
          follow_up_needed: !!data.follow_up_needed,
          follow_up_days: data.follow_up_days || 0
        }
        setFields(generated)
        lastSavedFields.current = JSON.stringify(generated)
        setReportStatus(data.status || 'draft')
        setReportId(data.report_id || null)
        setSynced(true)
        qc.invalidateQueries({ queryKey: ['reports'] })
        qc.invalidateQueries({ queryKey: ['consultations'] })
        toast.success('SOAP note generated by AI')
      }
    },
    onError: () => toast.error('SOAP generation failed'),
  })

  const exportMut = useMutation({
    mutationFn: (format: string) => {
      const targetId = reportId || consultationId
      return reportsApi.export(targetId, { format } as any)
    },
    onSuccess: (blob: any, format: string) => {
      if (blob) {
        const url = window.URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `SOAP_Report_${(reportId || consultationId).slice(0, 8)}.${format}`
        document.body.appendChild(a)
        a.click()
        window.URL.revokeObjectURL(url)
        document.body.removeChild(a)
        toast.success('Report exported successfully')
      } else {
        toast.error('Export failed: Empty file received')
      }
    },
    onError: () => toast.error('Export failed'),
  })

  const approveMut = useMutation({
    mutationFn: () => reportsApi.approve(consultationId),
    onSuccess: () => {
      setReportStatus('approved')
      qc.invalidateQueries({ queryKey: ['reports'] })
      qc.invalidateQueries({ queryKey: ['report', consultationId] })
      qc.invalidateQueries({ queryKey: ['consultations'] })
      toast.success('SOAP note approved and finalized')
    },
    onError: () => toast.error('Approval failed'),
  })

  const addMedication = () => {
    setFields(f => ({
      ...f,
      medications: [...f.medications, { name: '', dosage: '', frequency: '', duration: '', route: '', interaction_status: 'safe' }]
    }))
  }

  const updateMedication = (index: number, field: string, value: string) => {
    setFields(f => {
      const newMeds = [...f.medications]
      newMeds[index] = { ...newMeds[index], [field]: value }
      return { ...f, medications: newMeds }
    })
  }

  const removeMedication = (index: number) => {
    setFields(f => ({
      ...f,
      medications: f.medications.filter((_, i) => i !== index)
    }))
  }

  const SECTIONS = [
    { key: 'subjective', label: 'S — Subjective', color: '#5a3fad', placeholder: "Patient's chief complaint, history, and symptoms…" },
    { key: 'objective', label: 'O — Objective', color: '#0e7c4a', placeholder: 'Physical exam findings, vitals, and measurements…' },
    { key: 'assessment', label: 'A — Assessment', color: '#e67e22', placeholder: 'Clinical diagnosis and differential diagnoses…' },
    { key: 'plan', label: 'P — Plan', color: '#2980b9', placeholder: 'Treatment plan, medications, and follow-up…' },
  ]

  if (reportLoading) return <div style={{ textAlign: 'center', padding: 40, color: 'var(--text-3)' }}><Loader2 size={24} style={{ animation: 'spin 1s linear infinite' }} /></div>

  return (
    <div style={{ maxHeight: '75vh', overflowY: 'auto', paddingRight: 8 }}>
      <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 12 }}>
        {reportStatus === 'approved' && (
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, color: '#059669', marginRight: 14, fontWeight: 700 }}>
            <CheckCircle size={12} /> Approved
          </div>
        )}
        {isAutoSaving && (
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, color: 'var(--text-3)' }}>
            <Loader2 size={12} className="animate-spin" /> Auto-saving draft…
          </div>
        )}
        {!isAutoSaving && (
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, color: '#0e7c4a' }}>
             All changes saved
          </div>
        )}
      </div>

      {!synced && (
        <div style={{ marginBottom: 20, padding: '14px 18px', background: '#5a3fad10', border: '1px solid #5a3fad30', borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <span style={{ fontSize: 13, color: 'var(--text-2)' }}>No SOAP note found. Generate one from the consultation transcript.</span>
          <button
            onClick={() => generateMut.mutate()}
            disabled={generateMut.isPending}
            style={{ padding: '7px 16px', background: '#5a3fad', color: '#fff', border: 'none', borderRadius: 7, fontSize: 12.5, fontWeight: 500, cursor: 'pointer' }}
          >
            {generateMut.isPending ? 'Generating…' : '✦ Generate with AI'}
          </button>
        </div>
      )}

      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        {SECTIONS.map(({ key, label, color, placeholder }) => (
          <div key={key}>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 700, color, marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{label}</label>
            <textarea
              value={fields[key as keyof typeof fields] as string}
              onChange={(e) => setFields((f) => ({ ...f, [key]: e.target.value }))}
              placeholder={placeholder}
              className="form-control"
              rows={4}
              style={{ 
                resize: 'vertical', 
                fontFamily: 'inherit', 
                lineHeight: 1.6,
                background: reportStatus === 'approved' ? 'var(--surface-hover)' : 'var(--surface)',
                cursor: reportStatus === 'approved' ? 'default' : 'text'
              }}
              readOnly={reportStatus === 'approved'}
            />
          </div>
        ))}

        {/* Medications Section */}
        <div style={{ marginTop: 10 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>
            <label style={{ fontSize: 12, fontWeight: 700, color: 'var(--text-1)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Medications</label>
            {reportStatus !== 'approved' && (
              <button onClick={addMedication} className="btn btn-sm btn-outline" style={{ padding: '4px 10px', fontSize: 11 }}>+ Add Med</button>
            )}
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {fields.medications.length === 0 ? (
              <div style={{ fontSize: 12, color: 'var(--text-4)', fontStyle: 'italic', padding: '10px', border: '1px dashed var(--border)', borderRadius: 8, textAlign: 'center' }}>No medications prescribed</div>
            ) : (
              fields.medications.map((med, i) => (
                <div key={i} style={{ display: 'grid', gridTemplateColumns: '1.5fr 1fr 1fr 1fr 0.5fr', gap: 8, background: 'var(--surface-hover)', padding: 10, borderRadius: 8, border: '1px solid var(--border)' }}>
                  <input placeholder="Name" value={med.name} onChange={e => updateMedication(i, 'name', e.target.value)} disabled={reportStatus === 'approved'} className="form-control" style={{ marginBottom: 0, height: 32, fontSize: 12 }} />
                  <input placeholder="Dosage" value={med.dosage} onChange={e => updateMedication(i, 'dosage', e.target.value)} disabled={reportStatus === 'approved'} className="form-control" style={{ marginBottom: 0, height: 32, fontSize: 12 }} />
                  <input placeholder="Freq" value={med.frequency} onChange={e => updateMedication(i, 'frequency', e.target.value)} disabled={reportStatus === 'approved'} className="form-control" style={{ marginBottom: 0, height: 32, fontSize: 12 }} />
                  <input placeholder="Dur" value={med.duration} onChange={e => updateMedication(i, 'duration', e.target.value)} disabled={reportStatus === 'approved'} className="form-control" style={{ marginBottom: 0, height: 32, fontSize: 12 }} />
                  {reportStatus !== 'approved' && (
                    <button onClick={() => removeMedication(i)} style={{ border: 'none', background: 'transparent', color: '#e74c3c', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>✕</button>
                  )}
                </div>
              ))
            )}
          </div>
        </div>

        {/* Follow-up Section */}
        <div style={{ marginTop: 10, padding: 14, background: 'var(--surface-hover)', borderRadius: 10, border: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: 20 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <input 
              type="checkbox" 
              id="follow_up_needed" 
              checked={fields.follow_up_needed} 
              onChange={e => setFields(f => ({ ...f, follow_up_needed: e.target.checked }))} 
              disabled={reportStatus === 'approved'}
            />
            <label htmlFor="follow_up_needed" style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-1)' }}>Follow-up needed</label>
          </div>
          {fields.follow_up_needed && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <label style={{ fontSize: 12, color: 'var(--text-3)' }}>In</label>
              <input 
                type="number" 
                value={fields.follow_up_days} 
                onChange={e => setFields(f => ({ ...f, follow_up_days: parseInt(e.target.value) || 0 }))} 
                disabled={reportStatus === 'approved'}
                className="form-control" 
                style={{ width: 60, marginBottom: 0, height: 32, fontSize: 12 }} 
              />
              <span style={{ fontSize: 12, color: 'var(--text-3)' }}>days</span>
            </div>
          )}
        </div>
      </div>


      <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 20 }}>
        <button
          onClick={() => exportMut.mutate('pdf')}
          disabled={exportMut.isPending}
          style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 18px', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8, fontSize: 13, fontWeight: 500, cursor: 'pointer', color: 'var(--text-1)' }}
        >
          <Download size={14} /> {exportMut.isPending ? 'Exporting…' : 'Export PDF'}
        </button>
        <button
          onClick={() => saveMut.mutate()}
          disabled={saveMut.isPending || reportStatus === 'approved'}
          style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 18px', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8, fontSize: 13, fontWeight: 500, cursor: 'pointer', color: 'var(--text-1)' }}
        >
          <Save size={14} /> {saveMut.isPending ? 'Saving…' : 'Save Draft'}
        </button>
        <button
          onClick={() => approveMut.mutate()}
          disabled={approveMut.isPending || reportStatus === 'approved'}
          style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 18px', background: reportStatus === 'approved' ? '#94a3b8' : '#0e7c4a', color: '#fff', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 500, cursor: reportStatus === 'approved' ? 'not-allowed' : 'pointer' }}
        >
          <CheckCircle size={14} /> {reportStatus === 'approved' ? 'Approved' : approveMut.isPending ? 'Approving...' : 'Approve & Finalize'}
        </button>
      </div>
    </div>
  )
}
